services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
  users-api:
    build: 
      context: .
      dockerfile: apps/users-api/Dockerfile
    container_name: users_api
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      PORT: 3000
      SERVICE_NAME: users  #can't use name because linux use it for pc name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      




volumes:
  postgres_data: 