version: "3"
services:     # list all services for your application
  cm-athletes:  # name of your service
    image: claesweb/cm-athletes:latest  # image name
    ports: [ "3000:3000" ]  # port mapping
    restart: always  # restart policy

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db_data/:/data/./db_data/:/data/db/
      - /ect/timezone:/ect/timezone:ro
    ports:
      - 27017:27017
    networks:
      - backend-networks

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=123456
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - backend-networks

  cm-competitions:
    image: claesweb/cm-competitions:latest
    restart: always
    ports:
      - 3001:3000
    environment:
      - MONGO_URI=mongodb://mongo:27017/competitions
    networks:
      - backend-networks

  cm-frontend:
    image: claesweb/cm-frontend:latest
    ports: [ "80:3000" ]
    restart: always


networks:
  backend-networks:
    driver: bridge
