services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:               #I changed volume because of ownership issue but didn't really understand it
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: users_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres


volumes:
  postgres_data: