name: Manual Deployment - Build and Push All Apps

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (staging or prod)'
        required: true
        default: 'prod'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push All Apps
        run: |
          for app in apps/*; do
            if [ -d "$app" ]; then
              app_name=$(basename "$app")
              dockerfile="$app/Dockerfile"
              echo "Building and pushing Docker image for $app_name"
              docker build -f "$dockerfile" -t ${{ secrets.DOCKER_USERNAME }}/${app_name}:${{ github.event.inputs.environment }} .
              docker push ${{ secrets.DOCKER_USERNAME }}/${app_name}:${{ github.event.inputs.environment }}
            fi
          done

      - name: Build and Push Migrate DB
        run: |
          cd shared-packages/prisma
          docker build -t ${{ secrets.DOCKER_USERNAME }}/migrate-db:${{ github.event.inputs.environment }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/migrate-db:${{ github.event.inputs.environment }}

  deploy-manual:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Manual VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          script: |
            path="./CompetitionManagerSaasPrivate/${{ github.event.inputs.environment }}"
            cd $path
            docker-compose pull
            docker-compose up -d
