name: CI Workflow - Install, Lint, Test, and Build

on:
  push:
    branches:
      - '**'

jobs:
  ci:
    name: Install, Build, and Prepare for Lint/Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies for Apps and Shared Packages
        run: |
          for folder in apps/* shared-packages/*; do
            if [ -f "$folder/package.json" ]; then
              echo "Installing dependencies for $folder"
              cd "$folder"
              npm ci
              cd ../..
            fi
          done

      - name: Lint All Apps and Shared Packages (Placeholder)
        # run: |
        #   for folder in apps/* shared-packages/*; do
        #     if [ -f "$folder/package.json" ]; then
        #       echo "Linting $folder"
        #       cd "$folder"
        #       npm run lint
        #       cd ../..
        #     fi
        #   done
        run: |
          echo "Lint step is not implemented yet for apps and shared-packages"

      - name: Test All Apps and Shared Packages (Placeholder)
        # run: |
        #   for folder in apps/* shared-packages/*; do
        #     if [ -f "$folder/package.json" ]; then
        #       echo "Running tests for $folder"
        #       cd "$folder"
        #       npm test
        #       cd ../..
        #     fi
        #   done
        run: |
          echo "Test step is not implemented yet for apps and shared-packages"

      - name: Build All Apps and Shared Packages
        run: |
          for folder in apps/* shared-packages/*; do
            if [ -f "$folder/package.json" ]; then
              echo "Building $folder"
              cd "$folder"
              npm run build
              cd ../..
            fi
          done
